### ISSUE TITLE
望饼干更新适配legacy script engine🌹【enhancement】

### ISSUE THREAD

**Issue by superwfox** [lgc-LLSEDev/GoCQSync#1]
万事俱备 只欠东风！
lse引擎更新一个月里 各种插件也陆续在适配
gocqsync作为轻量的Bot群服插件
给无数腐竹留下了极好的印象 但岁月不饶人 gocqsync老矣
尚不能正常运行

希望作者可以提前更新日程 早日重构gocqsync
各位腐竹不胜感激🌹

**Comment by lgc2333** [comment]
NBSPlayer > LLBlackBEEx > GoCQSync(Will rename to LLSatori)
